#! /bin/sh
echo "... changing all scripts to executable"
chmod -x clean
chmod -x klein
chmod -x kleinc
chmod -x kleinf
chmod -x kleinp
chmod -x kleins
chmod -x kleinv

echo "... removing any existing classfiles"
cd src/src/
rm -f *.class
echo "... changing to src/ and compiling"

javac *.java
#echo "... moving classfiles to exe/"
#mv *.class ../../exe/
cd ../../
echo "... build complete"
