#! /Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4

import sys
from scanner      import src.Scanner
from fb_token     import src.Token
from td_parser    import src.Parser
from errors       import LexicalError, ParseError

try:
    filename = sys.argv[1]
    myfile   = open(filename)
    program  = myfile.read()

    scanner  = src.Scanner(program)
    parser   = src.Parser(scanner)
    is_valid = parser.parse()

    print(is_valid)
except LexicalError as le:
    print('Lexical error: ' + str(le))
except ParseError as le:
    print('Parse error: ' + str(le))
except Exception as exc:
    print('Something went wrong: ' + str(exc))
